export const LAST_USER_VISIT = 'LAST_USER_VISIT';
export const LAST_CURRENCY_LIST = 'LAST_CURRENCY_LIST';

export const COIN_API_KEY = `73034021-THIS-IS-SAMPLE-KEY`;

export const REFRESH_INTERVER = 10 * 1000;

export const LAST_RESENCENT_TIME = 3 * REFRESH_INTERVER;
